### ISSUE TITLE
Uses of MATLAB in src

### ISSUE THREAD

**Issue by milievski** [TataLab/iCubAudioAttention#5]
```CMakeList
if(ENABLE_MATLAB)
    add_subdirectory  ( gammatonePhase           )
    add_subdirectory  ( frequencyVisualisation   )
endif(ENABLE_MATLAB)
}
```

As we move away from the use of mex files to interface with MATLAB, I dont see the need to attempt to compile any more MATLAB code within our source folder. 

@reafrancesco should I remove compiling MATLAB for src? If there is any need to compile MATLAB mex file we can do it in the MATLAB folder?

**Comment by cognitiveinteraction** [comment]
We no longer need to compile MATLAB mex as far as I know. Surely frequencyVisualisation can be moved outside that IF branch. 
The gammatonePhase memorymaps output of the gammatone thread so it is using matlab but we no longer use it so it can be removed from the cmakelists.

**Comment by milievski** [comment]
All MATLAB code is now removed. The gammatonePhase is no longer getting completed if MATLAB is enabled
